spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
##加上mybatis-plus配置控制台打印完整带参数Sql语句
mybatis-plus:
   configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
